import type { Metadata } from "next";
import localFont from "next/font/local";
import "./ui/globals.css";
import { Toast } from "@/components/Toast";
import { ThemeProvider } from "@/components/Theme";
import { cn } from "@/lib/utils";
import SessionWrapper from "@/components/SessionWrapper/SessionWrapper";
import { QueryProvider } from "@/providers/QueryProvider";
import { SocketProvider } from "@/components/providers/socketProvider";

  const ggSans = localFont({
    src:[
      {path:"./fonts/ggsansRegular.ttf",weight:'200'},
      {path:"./fonts/ggsansMedium.ttf",weight:'400'},
      {path:"./fonts/ggsansSemibold.ttf",weight:'500'},
      {path:"./fonts/ggsansSemibold.ttf",weight:'500'},
      {path:"./fonts/ggsansBold.ttf",weight:'600 900'},
    ],
    variable:"--font-gg"
  })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

  <html lang="en" suppressHydrationWarning>
    <body className={cn(
      "font-sans antialiased min-h-screen h-screen overflow-hidden text-white",
      ggSans?.variable 
    )}>
      <QueryProvider>
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >
          <SocketProvider>
            <SessionWrapper>
            <Toast>

            <div className="flex">
              
              <div className="flex-col items-center w-full">
                
                <section className="">
                  {children}
                </section>

              </div>
            </div>

            </Toast>
            </SessionWrapper>
          </SocketProvider>
        </ThemeProvider>
      </QueryProvider>
    </body>
  </html>
  );
}
